### ISSUE TITLE
training 방식에 대한 질문입니다.

### ISSUE THREAD

**Issue by isangu** [ai4r/AIR-Action-Recognition#1]
training 코드를 살펴보다 의문점이 생겨 몇 가지 질문을 드리고자 합니다.

1. 학습 진행 시 전체 Training Data로 학습을 하는 것이 아닌 largeBatch를 두어 매 epoch마다 6,400개의 데이터로
학습을 진행하는 것 처럼 보이는데, 그렇게 진행하는 이유와
2. largeBatch 크기가 6,400으로 설정 된 이유
3. largeBatch 내에 Small Batch size를 랜덤하게 설정하시는 것 같았는데 그렇게 학습을 진행하는 것이 학습에 어떤 이점이 있는지

궁금하여 질문 드립니다.
감사합니다.

**Comment by jjh6297** [comment]
1. 매 Epoch별로 다 다른 Random Sampling 및 Sampling Rate을 주기 위해 데이터를 새로 읽어들입니다. 그래서 매번 6400개의 데이터를 읽어오고 있습니다.

2. 6400이란 숫자에는 큰 의미는 없습니다. Batch Size와 메모리를 고려해서 고른 숫자입니다.

3.  Batch Size의 크기에 의해서 지나치게 평균화되는 Gradient를 쓰게 되거나, 혹은 지나치게 Sample별 특성을 지닌 Gradient를 쓰게 됩니다. 이에 의해 성능 차이가 발생하게 되는데, 이를 다양하게 사용해 자유도를 높이려 그렇게 설정해두었습니다.
