### ISSUE TITLE
ETRI-Activity3D 데이터셋에 관한 문의

### ISSUE THREAD

**Issue by isangu** [ai4r/AIR-Action-Recognition#2]
데이터 셋 ETRI-Activity3D_Mat에 대해 궁금한 점이 있어 질문드립니다.  

1. 파일들이 (1, 284, 25, 3) 같은 shape으로 구성되어 있던데, 
1번째 항목이 프레임, 2번째 항목이 25개의 관절, 3번째 항목이 3d location으로 생각했는데 0번째 항목이 의미하는 바가 무엇인지
잘 모르겠습니다. 데이터에 대한 설명이 혹시 가능할까요?  

2. 25개 관절이 다음과 같은 모양으로 연결되어 있다고 생각하고, 데이터를 시각화하고자 했는데 결과가 예상했던 모양이랑 많이 달라 혹시 시각화 할 수 있다면 어떤 방식으로 해야하는지 알 수 있을까요?  

감사합니다.

**Comment by jjh6297** [comment]
1. 첫 번째 항목은 사람 숫자입니다. 행동에 따라서 사람이 한 명 들어있기도, 두 명 들어있기도 해서 그렇게 만들어 두었습니다.
    즉, (사람 수, 프레임 수, 관절 수, 3D Location)입니다.

2.  관절 연결에 관한 부분은 

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md

에서 BODY_25 버전을 따르고 있습니다.
